services:
  app:
    image: ghcr.io/versior/kaixin-ai:v0.1.0-kaixin.2
    container_name: infinite-canvas
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    ports:
      - "22380:3000"
    restart: unless-stopped
