services:
  app:
    image: ghcr.io/versior/kaixin-ai:v0.1.0-kaixin.8
    container_name: infinite-canvas
    env_file:
      - .env
    environment:
      - PUBLIC_IMAGE_BASE_URL=http://183.87.136.115:3000
    volumes:
      - ./data:/app/data
    ports:
      - "22380:3000"
      - "22381:8080"
    restart: unless-stopped
