services:
  app:
    image: ghcr.io/versior/kaixin-ai:main
    container_name: infinite-canvas
    env_file:
      - .env
    environment:
      - PUBLIC_IMAGE_BASE_URL=${PUBLIC_IMAGE_BASE_URL:-http://localhost:3000}
    volumes:
      - ./data:/app/data
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    restart: unless-stopped
